---
- hosts: all
  become: true
  tasks:
     - name: Download fullchain certificate
       get_url:
         url: https://drive.google.com/uc?export=download&id=0B7XAQYK_UhF5SDVtUUN3cXNBX00
         dest: /etc/tls/fullchain.pem

     - name: Download privkey certificate
       get_url:
         url: https://drive.google.com/uc?export=download&id=0B7XAQYK_UhF5TWdYZktyOFdwUnM
         dest: /etc/tls/privkey.pem

     - name: Ensure ssl_certificate = fullchain certificate
       lineinfile:
         path: /etc/nginx/conf.d/default.conf
         regexp: '^(.*)ssl_certificate'
         line: 'ssl_certificate /etc/tls/fullchain.pem;'

     - name: Ensure ssl_certificate_key = privkey certificate
       lineinfile:
         path: /etc/nginx/conf.d/default.conf
         regexp: '^(.*)ssl_certificate_key'
         line: ssl_certificate_key /etc/tls/privkey.pem;

  handlers:
     - name: restart nginx
       service:
         name: nginx
         state: restarted
